#start the docker image using ubuntu 20.10 as a
#starting point, name this ’base’
#the ubuntu image used by docker is very bare
#bones, you’ll need to pull in just about
#everything else

FROM ubuntu:20.10 AS base

#make sure all packages are up to date, install git (y is for answering yes to questions)
#Docker is not interactive

RUN apt update -y

FROM base AS builder

#compile the source code

RUN apt -y install clang-11 lldb-11 lld-11
RUN apt -y install clang
RUN apt -y install util-linux wget
RUN apt update -y

#download the repo (fix the linebreak:)
	#could use git pull
	#get directories working well
#only downloads things if there is a fail

RUN wget https://github.com/JBontes/CarlSAT_2021/archive/refs/heads/main.zip
RUN apt -y install unzip make

#and unzip
RUN ls main.zip | xargs -n1 unzip
RUN cd CarlSAT_2021-main/

#compile the source
RUN make clean && make

#fork a new image from the base...
FROM base as exec

#add the CarlSAT program
COPY --from=builder /CarlSAT_2021-main/CarlSAT .

#install python
RUN apt -y install python3

#copy your python project
COPY ./mypythonproject/mysource.* .

#Finally run the experiment and copy the log file to the host
CMD python3 mytest.py >> output.log && cp output.log /host/output.log

#note there can be only a single CMD line

#only installs if there are any differences from previous build
#uses checksum to check this

#when get wget error,comment those lines out of the docker file.
#it is because the ubunutu image doesn't have much else installed in it

#when using it the command is "docker build ."
#to name it: "docker build -t "name" . "
#then to run it, "docker run -it "name"

#building installs all dependencies (runs the runs)
#running calls the cmd command